from dataclasses import dataclass
from enum import Enum, auto


class Urgency(Enum):
    LOW = auto()
    NORMAL = auto()
    CRITICAL = auto()


@dataclass
class Notif:
    date: str
    hour: str
    title: str
    message: str
    urgency: Urgency = Urgency.NORMAL
    category: str = ""


@dataclass
class ScheduledNotif(Notif):
    """Uid is for notifications generated by calendar files"""

    uid: str = ""
