from dataclasses import dataclass
from enum import Enum


class Urgency(Enum):
    LOW = "low"
    NORMAL = "normal"
    CRITICAL = "critical"


@dataclass
class Notif:
    date: str
    hour: str
    title: str
    message: str
    urgency: Urgency = Urgency.NORMAL
    category: str = ""
    uid: str = ""  # Uid is for notifications generated by calendar files
